# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "HIYA HEALTH CHECKOUT"
client_id = "a84415693df813375e0c1f31fa59cef5"
application_url = "https://panasonic-backed-config-martha.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://panasonic-backed-config-martha.trycloudflare.com/auth/callback",
  "https://panasonic-backed-config-martha.trycloudflare.com/auth/shopify/callback",
  "https://panasonic-backed-config-martha.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "arctic-grey-sandbox.myshopify.com"
